trigger:
  batch: true
  branches:
    include:
      - "main"

variables:
- name: BuildPlatform
  value : 'x64'
- name: BuildConfiguration
  value: 'release'

resources:
  repositories:
    - repository: das-payments-v2-scheduledjobs
      type: github
      name: SkillsFundingAgency/das-payments-v2-scheduledjobs
      endpoint: SkillsFundingAgency

stages:
- stage: Build_Unit_Tests
  displayName: 'Build and Unit Tests'
  jobs:
  - template: pipeline-templates/job/code-build.yml
  - template: pipeline-templates/job/unittests.yml

- stage: Deploy_DST
  displayName: 'Deploy to DST'
  variables:
  - name: tagEnvironment
    value: Dev/Test
  - group: DCOL-DST - Environment Key Vault Secrets
  
  jobs:
  - template: pipeline-templates/deploy.yml
    parameters:
      pool: DCT
      environmentName: DST
      azureSubscription: DCT-VSO
      appName: DCOL-DST-ScheduledJobFunc-WEU

- stage: Deploy_DAS
  dependsOn: Deploy_DST
  displayName: Deploy to DAS
  variables:
  - name: tagEnvironment
    value: Dev/Test
  - group: DCOL-DAS - Environment Key Vault Secrets
  jobs:
  - template: pipeline-templates/deploy.yml
    parameters:
      pool: DCT
      environmentName: DAS
      azureSubscription: DCT-VSO
      appName: DCOL-DAS-ScheduledJobFunc-WEU

- stage: Deploy_SIT
  dependsOn: Deploy_DAS
  displayName: Deploy to SIT
  variables:
  - name: tagEnvironment
    value: Dev/Test
  - group: DCOL-SIT - Environment Key Vault Secrets
  jobs:
  - template: pipeline-templates/deploy.yml
    parameters:
      pool: DCT Build Pool
      environmentName: SIT
      azureSubscription: DCT-VSO
      appName: DCOL-SIT-ScheduledJobFunc-WEU

- stage: Deploy_SDW
  dependsOn: Deploy_SIT
  displayName: Deploy to SDW
  variables:
  - name: tagEnvironment
    value: Dev/Test
  - group: DCOL-SDW - Environment Key Vault Secrets
  jobs:
  - template: pipeline-templates/deploy.yml
    parameters:
      pool: DCT Build Pool
      environmentName: SDW
      azureSubscription: DCOL-Shadow
      appName: DCOL-SDW-ScheduledJobFunc-WEU