trigger:
  batch: true
  branches:
    include:
      - "main"

variables:
- name: BuildPlatform
  value : 'x64'
- name: BuildConfiguration
  value: 'release'

resources:
  repositories:
    - repository: das-payments-v2-scheduledjobs
      type: github
      name: SkillsFundingAgency/das-payments-v2-scheduledjobs
      endpoint: SkillsFundingAgency

stages:
- stage: Build_Unit_Tests
  displayName: 'Build and Unit Tests'
  jobs:
  - template: pipeline-templates/job/code-build.yml
  - template: pipeline-templates/job/unittests.yml

